package ec.edu.espe.customer.view;

import ec.edu.espe.customer.controller.CustomerController;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Maryuri Quiña, @ESPE
 */
public class FrmCustomer extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmCustomer.class.getName());

    /**
     * Creates new form FrmCustomer
     */
    public FrmCustomer() {
        initComponents();
    }
    
    /*¿Cómo lo adaptas si el examen cambia?
Si piden un dato más (ej. "Email"): Lo agregas a Customer.java (atributo y getter) y lo jalas en el controlador con doc.getString("email").

Si el cálculo cambia (ej. "Descuento"): Vas a Customer.java y cambias la fórmula en calculateTotal().

Si la tabla no muestra nada: Revisa en DatabaseConnection.java que el nombre de la base de datos sea idéntico al de tu MongoDB Compass.*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        btnLoadData = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblData);

        btnLoadData.setText("Load");
        btnLoadData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLoadData)
                .addGap(144, 144, 144))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 38, Short.MAX_VALUE)
                .addComponent(btnLoadData)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadDataActionPerformed
        // 1. Definimos las columnas de la tabla (Esto limpia y pone títulos nuevos)
    String[] columns = {"ID", "FULL NAME", "AMOUNT", "TOTAL (TAX)"};
    DefaultTableModel model = new DefaultTableModel(columns, 0);
    tblData.setModel(model);

    // 2. Llamamos al controlador
    CustomerController controller = new CustomerController();
    java.util.List<ec.edu.espe.customer.model.Customer> list = controller.getCustomersFromDatabase();

    // 3. Llenamos la tabla recorriendo la lista de objetos
    for (ec.edu.espe.customer.model.Customer c : list) {
        Object[] row = {
            c.getId(),
            c.getFullName(),
            c.getAmount(),
            c.calculateTotal() // Aquí se muestra el cálculo hecho en el modelo
        };
        model.addRow(row);
    }
    
    /*// EL BOTÓN SOLO LLAMA AL CONTROLADOR
    // Le pasamos la tabla 'tblData' como argumento
    new CustomerController().updateTable(tblData);*/
    }//GEN-LAST:event_btnLoadDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmCustomer().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoadData;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblData;
    // End of variables declaration//GEN-END:variables
}
